name = "Project Homepage"
license = "WTFPL"
licenselink = "https://github.com/donny-dont/hugo-project-homepage/blob/master/LICENSE.md"
description = "Hugo theme for developer projects"
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.15

[author]
  name = "Don Olmstead"
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
